// packages/ui/src/components/navigation-menu.tsx
import * as React from "react"
import { cva } from "class-variance-authority"
import { ChevronDownIcon } from "lucide-react"
import { NavigationMenu as NavigationMenuPrimitive } from "radix-ui"

import { cn } from "@pixler/ui/lib/utils"

function NavigationMenu({
  className,
  children,
  viewport = true,
  ...props
}: React.ComponentProps<typeof NavigationMenuPrimitive.Root> & {
  viewport?: boolean
}) {
  return (
    <NavigationMenuPrimitive.Root
      data-slot="navigation-menu"
      data-viewport={viewport}
      className={cn(
        "group/navigation-menu relative flex max-w-max flex-1 items-center justify-center",
        className
      )}
      {...props}
    >
      {children}
      {viewport && <NavigationMenuViewport />}
    </NavigationMenuPrimitive.Root>
  )
}

function NavigationMenuList({
  className,
  ...props
}: React.ComponentProps<typeof NavigationMenuPrimitive.List>) {
  return (
    <NavigationMenuPrimitive.List
      data-slot="navigation-menu-list"
      className={cn(
        "group flex flex-1 list-none items-center justify-center gap-1",
        className
      )}
      {...props}
    />
  )
}

function NavigationMenuItem({
  className,
  ...props
}: React.ComponentProps<typeof NavigationMenuPrimitive.Item>) {
  return (
    <NavigationMenuPrimitive.Item
      data-slot="navigation-menu-item"
      className={cn("relative", className)}
      {...props}
    />
  )
}

const navigationMenuTriggerStyle = cva(
  "group inline-flex h-9 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium transition-[color,box-shadow] outline-none hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus-visible:ring-[3px] focus-visible:ring-ring/50 focus-visible:outline-1 disabled:pointer-events-none disabled:opacity-50 data-[state=open]:bg-accent/50 data-[state=open]:text-accent-foreground data-[state=open]:hover:bg-accent data-[state=open]:focus:bg-accent"
)

function NavigationMenuTrigger({
  className,
  children,
  ...props
}: React.ComponentProps<typeof NavigationMenuPrimitive.Trigger>) {
  return (
    <NavigationMenuPrimitive.Trigger
      data-slot="navigation-menu-trigger"
      className={cn(navigationMenuTriggerStyle(), "group", className)}
      {...props}
    >
      {children}{" "}
      <ChevronDownIcon
        className="relative top-[1px] ml-1 size-3 transition duration-300 group-data-[state=open]:rotate-180"
        aria-hidden="true"
      />
    </NavigationMenuPrimitive.Trigger>
  )
}

function NavigationMenuContent({
  className,
  ...props
}: React.ComponentProps<typeof NavigationMenuPrimitive.Content>) {
  return (
    <NavigationMenuPrimitive.Content
      data-slot="navigation-menu-content"
      className={cn(
        "top-0 left-0 w-full p-2 pr-2.5 data-[motion=from-end]:slide-in-from-right-52 data-[motion=from-start]:slide-in-from-left-52 data-[motion=to-end]:slide-out-to-right-52 data-[motion=to-start]:slide-out-to-left-52 data-[motion^=from-]:animate-in data-[motion^=from-]:fade-in data-[motion^=to-]:animate-out data-[motion^=to-]:fade-out md:absolute md:w-auto",
        "group-data-[viewport=false]/navigation-menu:top-full group-data-[viewport=false]/navigation-menu:mt-1.5 group-data-[viewport=false]/navigation-menu:overflow-hidden group-data-[viewport=false]/navigation-menu:rounded-md group-data-[viewport=false]/navigation-menu:border group-data-[viewport=false]/navigation-menu:bg-popover group-data-[viewport=false]/navigation-menu:text-popover-foreground group-data-[viewport=false]/navigation-menu:shadow group-data-[viewport=false]/navigation-menu:duration-200 **:data-[slot=navigation-menu-link]:focus:ring-0 **:data-[slot=navigation-menu-link]:focus:outline-none group-data-[viewport=false]/navigation-menu:data-[state=closed]:animate-out group-data-[viewport=false]/navigation-menu:data-[state=closed]:fade-out-0 group-data-[viewport=false]/navigation-menu:data-[state=closed]:zoom-out-95 group-data-[viewport=false]/navigation-menu:data-[state=open]:animate-in group-data-[viewport=false]/navigation-menu:data-[state=open]:fade-in-0 group-data-[viewport=false]/navigation-menu:data-[state=open]:zoom-in-95",
        className
      )}
      {...props}
    />
  )
}

function NavigationMenuViewport({
  className,
  ...props
}: React.ComponentProps<typeof NavigationMenuPrimitive.Viewport>) {
  return (
    <div
      className={cn(
        "absolute top-full left-0 isolate z-50 flex justify-center"
      )}
    >
      <NavigationMenuPrimitive.Viewport
        data-slot="navigation-menu-viewport"
        className={cn(
          "origin-top-center relative mt-1.5 h-[var(--radix-navigation-menu-viewport-height)] w-full overflow-hidden rounded-md border bg-popover text-popover-foreground shadow data-[state=closed]:animate-out data-[state=closed]:zoom-out-95 data-[state=open]:animate-in data-[state=open]:zoom-in-90 md:w-[var(--radix-navigation-menu-viewport-width)]",
          className
        )}
        {...props}
      />
    </div>
  )
}

function NavigationMenuLink({
  className,
  ...props
}: React.ComponentProps<typeof NavigationMenuPrimitive.Link>) {
  return (
    <NavigationMenuPrimitive.Link
      data-slot="navigation-menu-link"
      className={cn(
        "flex flex-col gap-1 rounded-sm p-2 text-sm transition-all outline-none hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus-visible:ring-[3px] focus-visible:ring-ring/50 focus-visible:outline-1 data-[active=true]:bg-accent/50 data-[active=true]:text-accent-foreground data-[active=true]:hover:bg-accent data-[active=true]:focus:bg-accent [&_svg:not([class*='size-'])]:size-4 [&_svg:not([class*='text-'])]:text-muted-foreground",
        className
      )}
      {...props}
    />
  )
}

function NavigationMenuIndicator({
  className,
  ...props
}: React.ComponentProps<typeof NavigationMenuPrimitive.Indicator>) {
  return (
    <NavigationMenuPrimitive.Indicator
      data-slot="navigation-menu-indicator"
      className={cn(
        "top-full z-[1] flex h-1.5 items-end justify-center overflow-hidden data-[state=hidden]:animate-out data-[state=hidden]:fade-out data-[state=visible]:animate-in data-[state=visible]:fade-in",
        className
      )}
      {...props}
    >
      <div className="relative top-[60%] h-2 w-2 rotate-45 rounded-tl-sm bg-border shadow-md" />
    </NavigationMenuPrimitive.Indicator>
  )
}

export {
  NavigationMenu,
  NavigationMenuList,
  NavigationMenuItem,
  NavigationMenuContent,
  NavigationMenuTrigger,
  NavigationMenuLink,
  NavigationMenuIndicator,
  NavigationMenuViewport,
  navigationMenuTriggerStyle,
}

// files-from-my-angular-repo/ui/src/components/navigation-menu/navigation-menu.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  Directive,
  InjectionToken,
  ViewEncapsulation,
  computed,
  forwardRef,
  inject,
  input,
  signal,
} from '@angular/core';
import { cn } from '../../utils/cn';

export const NAV_MENU_TOKEN = new InjectionToken<NavigationMenuComponent>('NAV_MENU_TOKEN');
export const NAV_MENU_ITEM_TOKEN = new InjectionToken<NavigationMenuItemComponent>('NAV_MENU_ITEM_TOKEN');

// ── Root ─────────────────────────────────────────────────────────────────────

@Component({
  selector: 'ui-nav-menu',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  providers: [{ provide: NAV_MENU_TOKEN, useExisting: forwardRef(() => NavigationMenuComponent) }],
  host: {
    '[class]': 'computedClass()',
    '[attr.aria-label]': '"Main navigation"',
    '(keydown.escape)': 'closeAll()',
  },
  template: `
    <ul [class]="listClass()" role="list">
      <ng-content />
    </ul>
    <!-- Viewport slot for submenus -->
    <div class="absolute left-0 top-full z-50 w-full">
      <ng-content select="ui-nav-menu-viewport" />
    </div>
  `,
})
export class NavigationMenuComponent {
  readonly class = input<string>('');

  readonly activeItem = signal<string | null>(null);

  activate(id: string): void {
    this.activeItem.set(id);
  }
  closeAll(): void {
    this.activeItem.set(null);
  }
  toggle(id: string): void {
    this.activeItem.update((current) => (current === id ? null : id));
  }

  protected readonly computedClass = computed(() =>
    cn('relative z-10 flex max-w-max flex-1 items-center justify-center', this.class()),
  );
  protected readonly listClass = computed(() => 'group flex flex-1 list-none items-center justify-center space-x-1');
}

// ── List ─────────────────────────────────────────────────────────────────────

@Component({
  selector: 'ui-nav-menu-list',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    '[class]': 'computedClass()',
    role: 'list',
  },
  template: `<ng-content />`,
})
export class NavigationMenuListComponent {
  readonly class = input<string>('');
  protected readonly computedClass = computed(() =>
    cn('group flex flex-1 list-none items-center justify-center space-x-1', this.class()),
  );
}

// ── Item ──────────────────────────────────────────────────────────────────────

let _navMenuItemCounter = 0;

@Component({
  selector: 'ui-nav-menu-item',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  providers: [{ provide: NAV_MENU_ITEM_TOKEN, useExisting: forwardRef(() => NavigationMenuItemComponent) }],
  host: { '[class]': '"relative"' },
  template: `<ng-content />`,
})
export class NavigationMenuItemComponent {
  readonly _id = `nav-menu-item-${++_navMenuItemCounter}`;
  protected readonly _navMenu = inject(NAV_MENU_TOKEN);

  readonly isActive = computed(() => this._navMenu.activeItem() === this._id);

  toggle(): void {
    this._navMenu.toggle(this._id);
  }
  close(): void {
    this._navMenu.closeAll();
  }
}

// ── Trigger ───────────────────────────────────────────────────────────────────

@Component({
  selector: 'ui-nav-menu-trigger',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    '[class]': 'computedClass()',
    '[attr.aria-expanded]': '_item.isActive()',
    '[attr.data-state]': '_item.isActive() ? "open" : "closed"',
    '(click)': '_item.toggle()',
  },
  template: `
    <ng-content />
    <!-- Chevron icon -->
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="12"
      height="12"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      class="relative top-[1px] ml-1 h-3 w-3 transition duration-300"
      [class.rotate-180]="_item.isActive()"
      aria-hidden="true"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  `,
})
export class NavigationMenuTriggerComponent {
  readonly class = input<string>('');
  protected readonly _item = inject(NAV_MENU_ITEM_TOKEN);

  protected readonly computedClass = computed(() =>
    cn(
      'group inline-flex h-10 w-max cursor-pointer items-center justify-center rounded-md bg-background px-4 py-2 text-sm font-medium',
      'transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none',
      'disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50',
      'data-[state=open]:bg-accent/50',
      this.class(),
    ),
  );
}

// ── Content ───────────────────────────────────────────────────────────────────

@Component({
  selector: 'ui-nav-menu-content',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    @if (_item.isActive()) {
      <!-- Backdrop -->
      <div class="fixed inset-0 z-40" (click)="_item.close()"></div>
      <!-- Panel -->
      <div [class]="computedClass()" (keydown.escape)="_item.close()" (click)="$event.stopPropagation()">
        <ng-content />
      </div>
    }
  `,
})
export class NavigationMenuContentComponent {
  readonly class = input<string>('');
  protected readonly _item = inject(NAV_MENU_ITEM_TOKEN);

  protected readonly computedClass = computed(() =>
    cn(
      'absolute left-0 top-full z-50 w-auto rounded-md border bg-popover p-2 shadow-md',
      'animate-in fade-in-0 zoom-in-95 duration-200',
      this.class(),
    ),
  );
}

// ── Link ──────────────────────────────────────────────────────────────────────

@Directive({
  selector: 'a[uiNavMenuLink]',
  standalone: true,
  host: {
    '[class]': 'computedClass()',
  },
})
export class NavigationMenuLinkDirective {
  readonly class = input<string>('');
  readonly active = input<boolean>(false);

  protected readonly computedClass = computed(() =>
    cn(
      'block cursor-pointer select-none space-y-1 rounded-md p-2 leading-none no-underline outline-none transition-colors',
      'hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground',
      this.active() ? 'bg-accent/50' : '',
      this.class(),
    ),
  );
}
