// files-from-my-angular-repo/ui/src/components/scroll-area/scroll-area.component.ts
import { ChangeDetectionStrategy, Component, ViewEncapsulation, computed, input } from '@angular/core';
import { cn } from '../../utils/cn';

// ── Root ────────────────────────────────────────────────────────────────────

@Component({
  selector: 'ui-scroll-area',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: { '[class]': 'computedClass()' },
  template: `
    <!-- Viewport: the visible scrollable region -->
    <div
      class="h-full w-full overflow-auto rounded-[inherit]"
      style="scrollbar-width: thin; scrollbar-color: var(--color-border) transparent"
    >
      <ng-content />
    </div>
  `,
})
export class ScrollAreaComponent {
  readonly class = input<string>('');

  protected readonly computedClass = computed(() => cn('block relative overflow-hidden', this.class()));
}

// ── ScrollBar (optional; auto-hidden by CSS) ─────────────────────────────────

@Component({
  selector: 'ui-scroll-bar',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: { '[class]': 'computedClass()' },
  template: `<div class="relative flex-1 rounded-full bg-border"></div>`,
})
export class ScrollBarComponent {
  readonly orientation = input<'vertical' | 'horizontal'>('vertical');
  readonly class = input<string>('');

  protected readonly computedClass = computed(() => {
    const isVertical = this.orientation() === 'vertical';
    return cn(
      'flex touch-none select-none transition-colors',
      isVertical
        ? 'h-full w-2.5 border-l border-l-transparent p-[1px]'
        : 'h-2.5 flex-col border-t border-t-transparent p-[1px]',
      this.class(),
    );
  });
}

// packages/ui/src/components/scroll-area.tsx
"use client"

import * as React from "react"
import { ScrollArea as ScrollAreaPrimitive } from "radix-ui"

import { cn } from "@pixler/ui/lib/utils"

function ScrollArea({
  className,
  children,
  ...props
}: React.ComponentProps<typeof ScrollAreaPrimitive.Root>) {
  return (
    <ScrollAreaPrimitive.Root
      data-slot="scroll-area"
      className={cn("relative", className)}
      {...props}
    >
      <ScrollAreaPrimitive.Viewport
        data-slot="scroll-area-viewport"
        className="size-full rounded-[inherit] transition-[color,box-shadow] outline-none focus-visible:ring-[3px] focus-visible:ring-ring/50 focus-visible:outline-1"
      >
        {children}
      </ScrollAreaPrimitive.Viewport>
      <ScrollBar />
      <ScrollAreaPrimitive.Corner />
    </ScrollAreaPrimitive.Root>
  )
}

function ScrollBar({
  className,
  orientation = "vertical",
  ...props
}: React.ComponentProps<typeof ScrollAreaPrimitive.ScrollAreaScrollbar>) {
  return (
    <ScrollAreaPrimitive.ScrollAreaScrollbar
      data-slot="scroll-area-scrollbar"
      orientation={orientation}
      className={cn(
        "flex touch-none p-px transition-colors select-none",
        orientation === "vertical" &&
          "h-full w-2.5 border-l border-l-transparent",
        orientation === "horizontal" &&
          "h-2.5 flex-col border-t border-t-transparent",
        className
      )}
      {...props}
    >
      <ScrollAreaPrimitive.ScrollAreaThumb
        data-slot="scroll-area-thumb"
        className="relative flex-1 rounded-full bg-border"
      />
    </ScrollAreaPrimitive.ScrollAreaScrollbar>
  )
}

export { ScrollArea, ScrollBar }
